services:
  web:
    container_name: YTLocal
    build:
      context: .
      dockerfile: ./nextjs/Dockerfile
    ports:
      - "4000:3000"
    networks:
      - app_network
    privileged: true  # Grants the container additional privileges
    volumes:
      - "/home/damir/test:/host:rw,Z"
    stdin_open: true  # Keep stdin open (equivalent to `-i` flag)
    tty: true  # Allocate a pseudo-TTY (equivalent to `-t` flag)
    user: "1000:1000"
    command: bash -c "chown -R 1000:1000 /host && chmod -R 770 /host && node server.js"
    depends_on:
      - websocket
      - fileshare
  websocket:
    container_name: websocket
    build:
      context: .
      dockerfile: ./webSocket/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app_network

  fileshare:
    container_name: fileshare
    build:
      context: .
      dockerfile: ./fileShareServer/Dockerfile
    ports:
      - "4001:3000"
    networks:
      - app_network
    privileged: true  # Grants the container additional privileges
    volumes:
      - "/home/damir/test:/host:rw,Z"
    stdin_open: true  # Keep stdin open (equivalent to `-i` flag)
    tty: true  # Allocate a pseudo-TTY (equivalent to `-t` flag)
    user: "1000:1000"
    command: bash -c "chown -R 1000:1000 /host && chmod -R 770 /host && node server.js"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - websocket
      - fileshare
    networks:
      - app_network

networks:
  app_network:
    driver: bridge